version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - APP_ENV
      target: builder
    container_name: ${APP_NAME}-app
    command: npm run start:dev
    ports:
      - 3000:${APP_PORT}
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules/
    env_file:
      - .env
    depends_on:
      mssql:
        condition: service_started
    networks:
      - backend_network

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: ${APP_NAME}-database
    env_file:
      - .env
    ports:
      - 1433:${MSSQL_TCP_PORT}
    volumes:
      - sql_data:/var/opt/mssql
      - ./scripts/mssql-scripts:/mssql-scripts
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
    driver: bridge

volumes:
  sql_data:
