import { QueryRunner } from 'typeorm';

import { insertOrUpsertTable } from '../commons/functions';

export const inspectionItemTemplateTemplateData = async (
  queryRunner: QueryRunner,
) => {
  const data: {
    inspection_item_id: string;
    result_type: string;
    inspection_form_template_id: string;
    is_immutable_item: number;
    is_forced_required_item: number;
    position: number;
  }[] = [
    //1
    {
      inspection_item_id: '01HK4QBQJDXRCZ1BD4T44MMGXJ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4QBQJD17KT5ZEYA0N3HVYS',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4QBQJD0406HG49VHQ8NFKV',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4QBQJDNNTZWJ0XB2542Y36',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4QBQJEFT788311KJS1HWH9',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4QBQJEQV14AKHR3K9VPQKP',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4QBQJEAAV2Y3FZCK2MXDBX',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4QBQJEHJA5D4NM03SRWR0B',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4QBQJEHAGVSPE9M8MV887J',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4QFQ1AEVDQYFPYE8HDTX40',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 10,
    },
    {
      inspection_item_id: '01HK4R8HHE4E5R0SKKTJ03RGPR',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75F5HZFJ44679AV6H115CW',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 11,
    },
    //2
    {
      inspection_item_id: '01HK4R9TN6ATSX3EKPX8SAP3CC',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4R9TN723N5286RHTR1GZ74',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4R9TN75GE24YR06M28H8WE',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4R9TN78PB15KYDM3ADKRBD',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4R9TN7FXK32NVYVQ3MPY90',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4R9TN7EKDQ76Q4XYN87EWH',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4R9TN7VSK08626X3ERGZAG',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4R9TN7RRXCFXHF0YPAMXD1',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4R9TN8CB8BP9A3K8A3B82Y',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4R9TN8G1NSF03X4VG3ETMP',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4R9TN8BCJYTWZ03ZG9C2WN',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4RFYKQ033YWMWFP1WFV0NH',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 12,
    },
    {
      inspection_item_id: '01HK4RH324E04ENEDWY3A5DXEH',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75FPW6960DGWSMP1QQT7RD',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 13,
    },
    //3
    {
      inspection_item_id: '01HK4RP8TECEV3EZF7THV1NJRG',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4RP8TFG47A071JVE4DKDRE',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4RP8TFKKBTNG06616SDYZC',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4RP8TFGY8VJFTJQEC84MF2',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4RP8TFPVBKEA5Q1YFWQW6G',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4RP8TFTKAD1HV9J5GQ85ZR',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4RP8TFA2CTFBQT91PW1GH3',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4RP8TFYEH1SEXA1XN4YT6J',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4RP8TGCCH7WTKFKWRT15C9',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4RP8TGZTFF9JXPVVJHPRKV',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4RP8TGET49KR74MX9DZW3D',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4RP8TGDD68VECWBE23AC6V',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    {
      inspection_item_id: '01HK4RP8TG0J803JXSC97RYM2S',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 13,
    },
    {
      inspection_item_id: '01HK4RWHA1KB1MR1KNRX3MDK9W',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 14,
    },
    {
      inspection_item_id: '01HK4RWYRZ292RP7GCABJ77Y14',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75G5R0H69C2NWY3ARKJWV4',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 15,
    },
    //4
    {
      inspection_item_id: '01HK4SF4D94DRZ9THKJWNE8AM5',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4SF4D9JMNJKKGTSRZFT6PV',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4SF4DA4WVN5AN24XSG1M3A',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4SF4DAHYXF5B2KHKGE7VGV',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4SF4DAFTC3DDGASF60QZ4B',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4SF4DAX7YJBX0V5ZAJ7TMQ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4SF4DAP9MSKN9R5CESEFBK',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4SF4DAAYHZYJZA2H1HRP4M',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4SF4DASTV3GKP0V40BAZS3',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4SF4DAXXCFVXHRR4YB51AW',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4SF4DA8D1HPM7KBCQWDAAD',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4SF4DBVQ75HKDW8262HWQM',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    {
      inspection_item_id: '01HK4SF4DBT268PWRX8HX5ZV42',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 13,
    },
    {
      inspection_item_id: '01HK4SF4DBRPCRSBMJF4N71S50',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 14,
    },
    {
      inspection_item_id: '01HK4SMSYXR4TJDN8CAFD281N6',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 15,
    },
    {
      inspection_item_id: '01HK4SNVEVCHDR3VZ2B6WCV0E9',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75GHE53EM9QXT0J9WVZF6Z',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 16,
    },
    //5
    {
      inspection_item_id: '01HK4SS2SQS7D6JZKBKTYM605T',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4SS2SQF9NAQ1H25RQXFT91',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4SS2SQB1S2S7FP9EJQCNF2',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4SS2SQ7Z47HEKKXWKH26TD',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4SS2SQVA3QVS2Q85RBKNP3',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4SS2SRQKSRHEX6CTS4AZV3',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4SS2SREDQ3KS4ZPC9ERB8P',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4SS2SRMH9F72VRWGNPNF5Y',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4SS2SRC182QHTFMSQAA8M0',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4SS2SRKX30R7VKBG8K7TS3',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4SS2SRV92KVAKK9C7HHF9N',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4SS2SR18C29ZQEBDZBSWRK',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    {
      inspection_item_id: '01HK4SS2SR913KTB7CFT40BQEH',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 13,
    },
    {
      inspection_item_id: '01HK4SS2SRD5PRHXFM948FB1MF',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 14,
    },
    {
      inspection_item_id: '01HK4SS2SRPQE85GJW6J3WBNKQ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 15,
    },
    {
      inspection_item_id: '01HK4SZ1JD878Z6VBPCS5XDEQ1',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 16,
    },
    {
      inspection_item_id: '01HK4SZY91MM2RV9J2D5C2YXRM',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75GXBXWM0JTA19E4WWZB0C',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 17,
    },
    //6
    {
      inspection_item_id: '01HK4T101QSG2T3ED0XG3Q5E8F',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4T101Q1K774P93CQX4QCJW',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4T101QFR9D7D56C4MAPVKF',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4T101QV2PEM91GN9BF07JS',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4T101QDC4Y7742MSWA42KH',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4T101RWP6GMA8FG1NBJG8H',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4T101R65T6BJMMZTMC0T7P',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4T101RT8NDVFVAYHJ3C6YS',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4T101RQ767DZ39QP00MWTZ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4T101RTWC90K2A50H4Q8GP',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4T101RHBRK1V94B6RRHGW3',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4T101R27XQ3J6M7MMB103T',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    {
      inspection_item_id: '01HK4T101RWGTK92JGKJNNZQ58',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 13,
    },
    {
      inspection_item_id: '01HK4T101RTWD5T2PB7CX2D320',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 14,
    },
    {
      inspection_item_id: '01HK4T101RKDPTGJ352NN16YPM',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 15,
    },
    {
      inspection_item_id: '01HK4T70XCDRMZNCPV41HKZFWE',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 16,
    },
    {
      inspection_item_id: '01HK4T7M097W0J2B63D2A51167',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75H7JSF9KAXZJZVNVXWYJP',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 17,
    },
    //7
    {
      inspection_item_id: '01HK4T8MDD8TRPF31W4B9Z8AST',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4T8MDDX1JAWPF7RSS5A3A5',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4T8MDENHWM7YDE59NGNF85',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4T8MDEAWPEAZR1EHF4GMB5',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4T8MDE8MTEBTNJRMYAQTT7',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4T8MDFWR70N66Q5AJGDTFK',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4T8MDF7WEAVWHR8Q432P15',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4T8MDFQRRPZQXYEDTQ968V',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4T8MDFYPF6M7KVKV36B7ZQ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4T8MDF5T3E60D2XN3WB2S4',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4T8MDG0R29M49MNZGHW73W',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4T8MDGN9Z8SC1M39GFP9VA',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    {
      inspection_item_id: '01HK4T8MDG8D0F0K04XH3GE9JJ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 13,
    },
    {
      inspection_item_id: '01HK4T8MDG2S56F07BAH3GX2DP',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 14,
    },
    {
      inspection_item_id: '01HK4TEQQ8FPGRKE6BZM365WM9',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 15,
    },
    {
      inspection_item_id: '01HK4TFCXMHC2F6FNPC4N4M90V',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75HW616W08FE29SHVGS14F',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 16,
    },
    //8
    {
      inspection_item_id: '01HK4TH7TK4326QFZCF1JW65TF',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4TH7TMEBA4JBDPW3QE9ZQS',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4TH7TM3VKWBNWP4V3H8Q6Z',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4TH7TMZKGCV3CEHZ7JZ8QE',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4TH7TNWMJ1MMZ12DFCXDV4',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4TH7TNFCFCNM5QWZKVYVFW',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4TH7TNAGRH4W0Q5431BQZ1',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4TH7TN8N6XWG89TSJK14VD',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4TH7TP63H93066X40HDAR6',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4TH7TP6GJ1691PYX8NHR0Q',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4TNKZS4FE9YWASZ69HZZN2',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 11,
    },
    {
      inspection_item_id: '01HK4TPA3936DBN3CVFF4RX7Z9',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75J702NPW1TFFAQB13P6ND',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 12,
    },
    //9
    {
      inspection_item_id: '01HK4TQMTXQFQVK5362AF7ZGFY',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4TQMTYCSM84FJ5D489BV0T',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4TQMTYCSH5PVKRMMYBAKQD',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4TQMTYRJACJJ25BS70BBPN',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4TQMTYY6CF3FD2GQCG6PND',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4TQMTY0TVVGRKN61EM0ANM',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4TQMTYPX09SX14M2J8ZYHG',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4TQMTZS480KP36NC0YH1AV',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4TQMTZEG4F653FVY0629HT',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4TQMTZCKHHTG2Y490D1KG1',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4TQMTZ2JE3DFVACE4DMGWV',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4TQMTZMJF3HMB5GY1GJSEK',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    {
      inspection_item_id: '01HK4TQMTZNDZGFTSP1ADFEB1M',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 13,
    },
    {
      inspection_item_id: '01HK4TQMTZP9VGJTJMZBWY5775',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 14,
    },
    {
      inspection_item_id: '01HK4TQMTZZ99T46G0MPNTXNX4',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 15,
    },
    {
      inspection_item_id: '01HK4TQMV0BZ3JCMWNRNRRX1N5',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 16,
    },
    {
      inspection_item_id: '01HK4VHYQ31E2SDKESDC58FN3S',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 17,
    },
    {
      inspection_item_id: '01HK4VK1QPYFWWQV3MYZZ0TFFB',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75JFSVWHEVTWYVHEBBHZS5',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 18,
    },
    //10
    {
      inspection_item_id: '01HK4VN3TBXE4P9B51PBC59AM8',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4VN3TCJ1JYSK3PSMG4T20S',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4VN3TCNEVHP5JCVKWRKC7J',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4VN3TCSYK8F1B6CWMDWS9E',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4VN3TCEX5Q7GJNDWVG4KKC',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4VN3TC8CCPRM2A8Y6T4CCW',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4VN3TCJZZWHVB5V6A379YZ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4VN3TCYD30244SDWN56N23',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4VN3TC3HF02C5FE0G49DWT',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4VN3TCSJNPT30F4FBX4HM7',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4VN3TCHV82E9ZS85YNBA89',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4VN3TCESMMAPC72RPX2Q9P',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    {
      inspection_item_id: '01HK4VN3TDMQH7G205ET72JTCR',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 13,
    },
    {
      inspection_item_id: '01HK4VN3TD9AZHWK16YFVRGGXA',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 14,
    },
    {
      inspection_item_id: '01HK4VN3TD9PTZQ846D9MRZC81',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 15,
    },
    {
      inspection_item_id: '01HK4VN3TD99ZWFT7CVFM1C2YS',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 16,
    },
    {
      inspection_item_id: '01HK4VN3TD2XX6TWN867JCBPVQ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 17,
    },
    {
      inspection_item_id: '01HK4VN3TD15RNKTMBMTYV7V9J',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 18,
    },
    {
      inspection_item_id: '01HK4VN3TDF01ZM9GBXZDR4K1S',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 19,
    },
    {
      inspection_item_id: '01HK4VV99TETE7B4EGX5ZC5QPS',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 20,
    },
    {
      inspection_item_id: '01HK4VVTSJX7ZEW3K53QSKXCZE',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75JV46Q1HV6F7XBR8V1NKA',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 21,
    },
    //11
    {
      inspection_item_id: '01HK4VWZVEHGK19HY0GZP9EWWD',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4VWZVECWJT1ETD8SD96HMR',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4VWZVE51QPHHF1599JXAR6',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4VWZVFNC15FM3E8TRMHGE3',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4VWZVFK10E2NYRXAZ8Z7CZ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4VWZVF50Y2AA5DZATD1KZV',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4VWZVF6ZC6T2BARZYR3ES7',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4VWZVFGKHFQBFV4X6SS9XX',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4VWZVF74H3C20PWE9SHKM6',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4VWZVFRA5KJKC9ZMJSP22K',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4VWZVGT0DXZFNMZPXNBBZ0',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4W1TZDE8YH52NTS6P8SZ3R',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 12,
    },
    {
      inspection_item_id: '01HK4W2J6JFNH66YVKJQFN2DR7',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75K7HB9CVNGSP4MWRZERXB',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 13,
    },
    //12
    {
      inspection_item_id: '01HK4W4AW8BQ2TZ1ZW7CP661NK',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4W4AW9KY6H30P5V1QR6Z76',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4W4AW9VEZGDAPGA63B005N',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4W4AW9CWFF6C9F5TFVG3BD',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4W4AW988BFPVDRSXM350Z0',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4W4AW9NHN4XKC6Y1W55ASF',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4W4AW9T0NX81M28WY11TXY',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4W4AW9RSX0KBXBBTQ181HF',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4W4AW9KK0NSQZ5F64P9C5D',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4W4AW9AFX2ZCQRKNS6S60P',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4W87H8YCQ69F8NJPD8WMDT',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4W9JA2TZPBKKSZAHSJD7G9',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75KH58B8GM11NT1EBJFWPT',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    //13
    {
      inspection_item_id: '01HK4WACNZQTZP6NB36VE5X7PC',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 1,
    },
    {
      inspection_item_id: '01HK4WACNZ49ADD78HCD4KNVQ9',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 2,
    },
    {
      inspection_item_id: '01HK4WACNZG48RXGTVHYYY1PBT',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 3,
    },
    {
      inspection_item_id: '01HK4WACNZXKXQ1STSB3R8330E',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 4,
    },
    {
      inspection_item_id: '01HK4WACP0TKNW2E2ENJDWPJEG',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 5,
    },
    {
      inspection_item_id: '01HK4WACP085TP9NY5HKGCRKCC',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 6,
    },
    {
      inspection_item_id: '01HK4WACP0BQPHCKKEV8AQANXD',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 7,
    },
    {
      inspection_item_id: '01HK4WACP0NN66HK3QMFEQHQ7R',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 8,
    },
    {
      inspection_item_id: '01HK4WACP1CDWH6K22EAD0PNBS',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 9,
    },
    {
      inspection_item_id: '01HK4WACP3BEK5EQCVXYZED95Q',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 10,
    },
    {
      inspection_item_id: '01HK4WACP4TSFPJZJA2C6NH64Y',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 11,
    },
    {
      inspection_item_id: '01HK4WACP4JTFZHAD5E59N1TPQ',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 12,
    },
    {
      inspection_item_id: '01HK4WACP4CPWCWVKNHB3Z1NEC',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 13,
    },
    {
      inspection_item_id: '01HK4WACP4AFNJ3GZ2PJFSM6V7',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 14,
    },
    {
      inspection_item_id: '01HK4WACP44X5FEXGZJNMHQQ53',
      result_type: 'OK_OR_ANOMARY',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 0,
      is_forced_required_item: 0,
      position: 15,
    },
    {
      inspection_item_id: '01HK4WF3YNBPKQP4H9SQX5ZVYK',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 16,
    },
    {
      inspection_item_id: '01HK4WFSFNKZFJY1FBDWXJ9QG3',
      result_type: 'NUMERIC',
      inspection_form_template_id: '01HK75KTXQ83MWNP8TA8YNZGXA',
      is_immutable_item: 1,
      is_forced_required_item: 1,
      position: 17,
    },
  ];

  await insertOrUpsertTable(
    queryRunner,
    'inspection_item_templates',
    ['inspection_item_id', 'inspection_form_template_id'],
    data,
  );
};
