on:
  push:
    branches:
      - 'main'

name: App service Deploy

jobs:
  sprint_deploy:
    name: App service Deploy - Production
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      ENV: prd
      IMAGE_NAME: opeapp-prd-japanwest-webapp-secondary
      RESOURCE_GROUP: opeapp-prd-japaneast
      KEY_VAULT: opeappprdjapaneastkvapp
      APP_SERVICE: opeapp-prd-japanwest-webapp-secondary
      DOCKER_FILE: ./Dockerfile
      SLOT_NAME: preview
      branch_deploy: refs/heads/main
      script_setting_env: ./ops/app_setting_env_stg_prd.sh
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_PRD }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME_SECONDARY_PRD }}
