on:
  push:
    branches:
      - 'staging'

name: App service Deploy

jobs:
  sprint_deploy:
    name: App service Deploy - Staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      ENV: stg
      IMAGE_NAME: opeapp-stg-japaneast-webapp
      RESOURCE_GROUP: opeapp-stg-japaneast
      KEY_VAULT: opeappstgjapaneastkvapp
      APP_SERVICE: opeapp-stg-japaneast-webapp
      DOCKER_FILE: ./Dockerfile
      SLOT_NAME: preview
      branch_deploy: refs/heads/staging
      script_setting_env: ./ops/app_setting_env_stg_prd.sh
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_STG }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME_STG }}
